# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mediashelf-loggable}
  s.version = "0.4.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Patrick Reagan}, %q{Matt Zumwalt}]
  s.date = %q{2011-07-28}
  s.description = %q{A gem that provides logging capabilities to any class.  Relies on Rails logger if it's available.  Extended from loggable gem by viget}
  s.email = %q{matt.zumwalt@yourmediashelf.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     ".rvmrc",
     "Gemfile",
     "Gemfile.lock",
     "History.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/loggable.rb",
     "lib/loggable/log_methods.rb",
     "lib/loggable/logger_stub.rb",
     "lib/tasks/loggable.rake",
     "loggable.gemspec",
     "mediashelf-loggable.gemspec",
     "test/examples/log_methods_test.rb",
     "test/examples/logger_stub_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/mediashelf/mediashelf-loggable}
  s.rdoc_options = [%q{--charset=UTF-8}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{A gem that provides logging capabilities to any class}
  s.test_files = [
    "test/examples/log_methods_test.rb",
     "test/examples/logger_stub_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

